server:
  port: 8001

spring:
  application:
    name: chat-server
  redis:
    host: 10.211.55.4
    port: 6379
    database: 0
    jedis:
      pool:
        # 最大阻塞等待时间，负数表示没有限制
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 5
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中最大连接数，负数表示没有限制
        max-active: 20

# mybatis-plus配置
mybatis-plus:
  # xml文件位置
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cxy.entity

websocket:
  uri: /ws
  port: 8007
  expire: 200
